### ISSUE TITLE
Set up GitHub Actions

### ISSUE THREAD

**Issue by haerdib** [litentry/worker#14]
The worker comes with a very nice GitHub action workflow: https://github.com/litentry/worker/blob/litentry/.github/workflows/build_and_test.yml

It runs the following:
- unit tests ([cargo test](https://github.com/litentry/worker/blob/9d61c79aab8c71fafba4a292d8c7ad280b3a9ddf/.github/workflows/build_and_test.yml#L28-L29) testing the untrusted code & [enclave test](https://github.com/litentry/worker/blob/9d61c79aab8c71fafba4a292d8c7ad280b3a9ddf/.github/workflows/build_and_test.yml#L30-L33) testing all trusting code)
- Tests if the [build compiles](https://github.com/litentry/worker/blob/9d61c79aab8c71fafba4a292d8c7ad280b3a9ddf/.github/workflows/build_and_test.ym#L36-L52) (& uploads it) 
- runs [cargo clippy](https://github.com/litentry/worker/blob/9d61c79aab8c71fafba4a292d8c7ad280b3a9ddf/.github/workflows/build_and_test.ym#L54-L72) and fails if there's a clippy warning
- runs [cargo fmt](https://github.com/litentry/worker/blob/9d61c79aab8c71fafba4a292d8c7ad280b3a9ddf/.github/workflows/build_and_test.ym#L73-L88) and fails if there's a file not cargo fmt formatted
- runs [integration tests](https://github.com/litentry/worker/blob/9d61c79aab8c71fafba4a292d8c7ad280b3a9ddf/.github/workflows/build_and_test.ym#L91) together with the node:
    -  [M6](https://github.com/litentry/worker/blob/9d61c79aab8c71fafba4a292d8c7ad280b3a9ddf/client/demo_shielding_unshielding.sh): Testing if a shielding & unshielding trusted call sent to the node gets processed correctly in the enclave
    - [M8](https://github.com/litentry/worker/blob/9d61c79aab8c71fafba4a292d8c7ad280b3a9ddf/client/demo_direct_call.sh): Testing if a direct trusted call sent to the enclave RPC interface gets processed correctly in the enclave
    
I think it makes sense to have atleast the unit test, the build test, clippy and fmt GA integrated. If possible also the integration tests M6 (and M8). Later on we should change M6 to send account linker extrinsic, respective add a new test, whatever you prefer.

For the integration tests to run, we will need to update the integritee node repository and activate GA there as well.

What's your opinion on this mattter? @h4n0 @suinuj

**Comment by h4n0** [comment]
Yes, this is pretty nicely designed and I am glad to have all of these set up for our worker repo. 

I assume the enclave related tests should take place on a SGX machine, which is also possible for us. Let's sync this on tomorrow's meeting as well with a rough time estimation.

**Comment by h4n0** [comment]
Except M8 test, the rest has been completed already with the PR  #45
