### ISSUE TITLE
Dispatch Error: "LayerOneBlockNumberNotAvailable"

### ISSUE THREAD

**Issue by haerdib** [litentry/worker#21]
When calling into sgx-runtime pallet sgx-account-linker, the following error is returned: 

`Dispatch Error: "LayerOneBlockNumberNotAvailable"`

It should be looked into a little bit more to see if the error is on the pallet or worker side.
First thing to check would be is if the Storagehasher & storage key are identical on worker & pallet side.

**Comment by suinuj** [comment]
fixed with pr https://github.com/litentry/worker/pull/29
