### ISSUE TITLE
Account Systems mapping between enclave and parachain

### ISSUE THREAD

**Issue by h4n0** [litentry/worker#22]
In order to store users' account linking data on enclave, we ought to map the parachain account with enclave account.

There are still open points from my side:
- [ ] Can we share the same user address (SS58) on both sides?
- [ ] How would the transaction fee be paid on enclave side?

_Originally posted by @h4n0 in https://github.com/litentry/worker/pull/19#discussion_r728134080_

**Comment by Kailai-Wang** [comment]
closing stale issues
