### ISSUE TITLE
Find out a way of developing with a shared TEE server

### ISSUE THREAD

**Issue by h4n0** [litentry/worker#63]
Currently, we have only one server for running and testing our TEE network. We need to find out a solution for all developers to use the TEE server efficiently without disturbing each other.

Possible solutions:
1. Run worker on the local machine with simulation mode (does every CPU support the sw sim? Refer to CI, which runs in sim mode)
2. Open more servers 
3. Use different ports while starting the TEE testnet on the server (for multiple usages at the same time)

**Comment by h4n0** [comment]
https://www.notion.so/litentry/TEE-Server-Usage-Plan-981599304ca14243b13ff2fdee1ed8f3

**Comment by StamfordDigital** [comment]
Team agrees on a new TEE server for development.
