### ISSUE TITLE
Sync to upstream 5fa928d

### ISSUE THREAD

**Issue by Kailai-Wang** [litentry/worker#72]
We are 9 commits behind upstream and would like to sync with upstream commit [5fa928d](https://github.com/integritee-network/worker/commit/5fa928d641c5eb384035cb24a962237db33f4ceb)

This should include:
- dependency update to `polkadot-v0.9.20`
- dockerization of worker

**Comment by Kailai-Wang** [comment]
Maybe include the latest two commits too 😂 @h4n0 
https://github.com/integritee-network/worker/commits/master

**Comment by h4n0** [comment]
The colleagues from integritee helped me to keep that PR updated.

> Maybe include the latest two commits too 😂 @h4n0 https://github.com/integritee-network/worker/commits/master
