### ISSUE TITLE
panicked in ws_client

### ISSUE THREAD

**Issue by suinuj** [litentry/worker#74]
To verify the https support in TEE, I created a branch https-test for testing via send a trusted call query-credit.
The process as following:
1. start the node and worker via local-setup/launch.py
2. after the worker and node running, call query-credit via cli
RUST_BACKTRACE=full ./integritee-cli -P 2090 -p 9990 trusted --mrenclave 4GuW1gD2D4Bvg6t4A2b9W1vQZPgpmAv7kfL7yM5qYM89 query-credit //Alice

We get the panic and trace stack as:
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: SendError { .. }', core/rpc-client/src/ws_client.rs:114:43
stack backtrace:
   0:     0x55c40f280d9c - std::backtrace_rs::backtrace::libunwind::trace::h793e05efd273d0f4
                               at /rustc/8b09ba6a5d5c644fe0f1c27c7f9c80b334241707/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x55c40f280d9c - std::backtrace_rs::backtrace::trace_unsynchronized::h640b7b86ff610c77
                               at /rustc/8b09ba6a5d5c644fe0f1c27c7f9c80b334241707/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55c40f280d9c - std::sys_common::backtrace::_print_fmt::h362fa2a4f354f877
                               at /rustc/8b09ba6a5d5c644fe0f1c27c7f9c80b334241707/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x55c40f280d9c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hf439e5ed84c74abd
                               at /rustc/8b09ba6a5d5c644fe0f1c27c7f9c80b334241707/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x55c40f2a3f4c - core::fmt::write::h72801a82c94e6ff1
                               at /rustc/8b09ba6a5d5c644fe0f1c27c7f9c80b334241707/library/core/src/fmt/mod.rs:1149:17
   5:     0x55c40f27a7e5 - std::io::Write::write_fmt::h5562a8b6da0f0339
                               at /rustc/8b09ba6a5d5c644fe0f1c27c7f9c80b334241707/library/std/src/io/mod.rs:1697:15
   6:     0x55c40f282700 - std::sys_common::backtrace::_print::hb29ddd998d02631c
                               at /rustc/8b09ba6a5d5c644fe0f1c27c7f9c80b334241707/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x55c40f282700 - std::sys_common::backtrace::print::h81965e3d7c90fbb6
                               at /rustc/8b09ba6a5d5c644fe0f1c27c7f9c80b334241707/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x55c40f282700 - std::panicking::default_hook::{{closure}}::h84db205ab6674b38
                               at /rustc/8b09ba6a5d5c644fe0f1c27c7f9c80b334241707/library/std/src/panicking.rs:211:50
   9:     0x55c40f2822ab - std::panicking::default_hook::h1bf8bb4159936bca
                               at /rustc/8b09ba6a5d5c644fe0f1c27c7f9c80b334241707/library/std/src/panicking.rs:228:9
  10:     0x55c40f282db4 - std::panicking::rust_panic_with_hook::hf8e86850fbbd03b1
                               at /rustc/8b09ba6a5d5c644fe0f1c27c7f9c80b334241707/library/std/src/panicking.rs:606:17
  11:     0x55c40f282890 - std::panicking::begin_panic_handler::{{closure}}::h590a0d6060ff866e
                               at /rustc/8b09ba6a5d5c644fe0f1c27c7f9c80b334241707/library/std/src/panicking.rs:502:13
  12:     0x55c40f281254 - std::sys_common::backtrace::__rust_end_short_backtrace::h260b8bd1c848a03c
                               at /rustc/8b09ba6a5d5c644fe0f1c27c7f9c80b334241707/library/std/src/sys_common/backtrace.rs:139:18
  13:     0x55c40f2827f9 - rust_begin_unwind
                               at /rustc/8b09ba6a5d5c644fe0f1c27c7f9c80b334241707/library/std/src/panicking.rs:498:5
  14:     0x55c40efc23f1 - core::panicking::panic_fmt::h7b8580d81fcbbacd
                               at /rustc/8b09ba6a5d5c644fe0f1c27c7f9c80b334241707/library/core/src/panicking.rs:106:14
  15:     0x55c40efc24e3 - core::result::unwrap_failed::h885d3f7beb571353
                               at /rustc/8b09ba6a5d5c644fe0f1c27c7f9c80b334241707/library/core/src/result.rs:1613:5
  16:     0x55c40f03aa1b - <itc_rpc_client::ws_client::WsClient as ws::handler::Handler>::on_message::ha9c9e250b9f509aa
  17:     0x55c40f0702be - ws::connection::Connection<H>::read_frames::hd3ef89049a1b6d23
  18:     0x55c40f072a3d - ws::connection::Connection<H>::read::hd397d73e8784da6e
  19:     0x55c40f0629fb - ws::io::Handler<F>::handle_event::h22125c1ad8ba1650
  20:     0x55c40f069605 - ws::io::Handler<F>::run::h49bece0196ad8d7e
  21:     0x55c40f056d4e - ws::connect::h024093a120b4c878
  22:     0x55c40f039f9f - itc_rpc_client::ws_client::WsClient::connect_watch_with_control::h0c4c4c99cd43171c
  23:     0x55c40f04ff03 - std::sys_common::backtrace::__rust_begin_short_backtrace::hb186a2a135b387f6
  24:     0x55c40f050671 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h376c117743fbf1df
  25:     0x55c40f2860b3 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h771719d52c343434
                               at /rustc/8b09ba6a5d5c644fe0f1c27c7f9c80b334241707/library/alloc/src/boxed.rs:1694:9
  26:     0x55c40f2860b3 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hf441746dfa4b0f57
                               at /rustc/8b09ba6a5d5c644fe0f1c27c7f9c80b334241707/library/alloc/src/boxed.rs:1694:9
  27:     0x55c40f2860b3 - std::sys::unix::thread::Thread::new::thread_start::hfd168f9d312b29ca
                               at /rustc/8b09ba6a5d5c644fe0f1c27c7f9c80b334241707/library/std/src/sys/unix/thread.rs:106:17
  28:     0x7fd6383c6609 - start_thread
                               at /build/glibc-sMfBJT/glibc-2.31/nptl/pthread_create.c:477:8
  29:     0x7fd638194163 - clone
  30:                0x0 - <unknown>

**Comment by Kailai-Wang** [comment]
I can reproduce this.

However, the program continues to run despite having panic, and the trusted call can be correctly included in the sidechain block and seems to go through.

It's reproducible with `set-balance` too:
```
./bin/integritee-cli trusted --mrenclave 5zUh4rNpDdynhKrW29PmxHiD1hrdYNqyraeR4U4mbtwP --direct balance //AliceIncognito
0

./bin/integritee-cli trusted --mrenclave 5zUh4rNpDdynhKrW29PmxHiD1hrdYNqyraeR4U4mbtwP --direct set-balance //AliceIncognito 100000000000000
send trusted call set-balance(5Dt1Wg85pXGLstt36t6TDdvXXoCtG6zkUL17KkyVaPYSrzGH, 100000000000000)
thread '<unnamed>' panicked at 'error sending result: sending on a closed channel', core/rpc-client/src/ws_client.rs:116:23
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Trusted call 0x6825f0d9f62d4ebfe84f71832e217c723d35badeaa2aa0564b743dd63aee2c1f is Submitted
Trusted call 0x6825f0d9f62d4ebfe84f71832e217c723d35badeaa2aa0564b743dd63aee2c1f is InSidechainBlock(0xa138b60c777cec8c1093b243b39cd9258444c88e854e4e4c65adf6b63e4aa8fe)
kai@ns3181934:~/worker$

./bin/integritee-cli trusted --mrenclave 5zUh4rNpDdynhKrW29PmxHiD1hrdYNqyraeR4U4mbtwP --direct balance //AliceIncognito
100000000000000
```

The error itself is just about sending messages to a closed channel, but assume a new connection will be reinitiaized later, so from my perspective it's nice to get this fixed, but shouldn't be a blocker.

Do you see a different situation @suinuj ?

**Comment by suinuj** [comment]
We can ignore it now, but got a new error.
[2022-05-19T01:23:01Z ERROR ita_stf::stf_sgx_litentry] query_credit([d4, 35, 93, c7, 15, fd, d3, 1c, 61, 14, 1a, bd, 4, a9, 9f, d6, 82, 2c, 85, 58, 85, 4c, cd, e3, 9a, 56, 84, e7, a5, 6d, a2, 7d]
[2022-05-19T01:23:01Z ERROR ita_stf::stf_sgx_litentry] send https request result as Err(ComponentNotInitialized)
[2022-05-19T01:23:01Z DEBUG ita_stf::helpers] incrementing account nonce

**Comment by haerdib** [comment]
The cause of the error above:
```
thread '<unnamed>' panicked at 'error sending result: sending on a closed channel', core/rpc-client/src/ws_client.rs:116:23
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

is because of some not yet perfectly implemented client connection and sending update to it thereof. I wouldn't advise you to investigate there, because we will most likely fix it upstream with https://github.com/integritee-network/worker/issues/207. I'll keep you updated about the progress of that.

I'm currrently looking into the second one - I'll keep you updated

**Comment by haerdib** [comment]
I think the problem is here:

https://github.com/litentry/worker/blob/b844d0c71d3ebf8e9ef0b8f26faa066a0cb8a841/core/https-client-daemon/src/daemon_sender.rs#L34-L38

While it is a static, the Mutex is initialized empty (`Default::default` of an `Option` is `None`)

I believe the root cause is a missing call of https://github.com/litentry/worker/blob/b844d0c71d3ebf8e9ef0b8f26faa066a0cb8a841/core/https-client-daemon/src/daemon_sender.rs#L75 
It does not seem to be called anywhere

**Comment by Kailai-Wang** [comment]
Thanks @haerdib , I believe the problem is we never started https client daemon thread inside enclave?

I'm talking about
https://github.com/litentry/worker/blob/litentry/core-primitives/enclave-api/src/https_client_daemon.rs#L28
Can we try to start it during enclave initialisation? @suinuj

**Comment by suinuj** [comment]
I will try it.

**Comment by Kailai-Wang** [comment]
This is somewhat expected, as `HttpsRestClient::send()` probably always returns an error due to incorrect module ID and method ID (our parachain doesn't have a credit-score pallet).

https://github.com/litentry/worker/blob/15a2f64b6b9259f169f42da296f0da9b0d91943f/core/https-client-daemon/src/https_client.rs#L83-L86

IMHO it's enough to make sure we can send https request and get responses inside enclave. If we really want to test the passing back of results, we can add a dummy extrinsic for integration test in the future identity management pallet.

**Comment by suinuj** [comment]
Agree with @Kailai-Wang, there is no such pallet in litentry parachain. The branch just used to verify the https request and response, the log we got already enough to prove it works.

**Comment by suinuj** [comment]
I'd like to keep the issue open until the panic resolved in upstream and sync up to our worker. and it is low priority one.

**Comment by Kailai-Wang** [comment]
Sure :)

btw shall we have an integration test for HTTPS request/response?

**Comment by Kailai-Wang** [comment]
closing stale issues
